{% set version = "0.18.0" %}

package:
  name: prometheus_client
  version: {{ version }}

source:
  url: https://github.com/prometheus/client_python/archive/v{{ version }}.tar.gz
  sha256: a550e9856e1a992396d54145dd4078c887de590e58595d316e6efa59820a1d8f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - prometheus_client
    - prometheus_client.bridge
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/prometheus/client_python
  license: Apache-2.0
  summary: Python client for the Prometheus monitoring system
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jessicaaustin
    - kwilcox
    - ocefpaf
