{% set name = "prometheus_client" %}
{% set version = "0.1.1" %}
{% set build = 0 %}
{% set sha256 = "76420e051aba1e394fb85e8fd8eda4681e25094eec6ade6370a802fd45c43630" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/prometheus/client_python/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - twisted

test:
  imports:
    - prometheus_client
    - prometheus_client.bridge
    - prometheus_client.twisted

about:
  home: https://github.com/prometheus/client_python
  license: Apache 2.0
  summary: 'Python client for the Prometheus monitoring system.'
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jessicaaustin
    - kwilcox
