{% set name = "prometheus_client" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prometheus_client-{{ version }}.tar.gz
  sha256: 35f7a8c22139e2bb7ca5a698e92d38145bc8dc74c1c0bf56f25cca886a764e17

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - prometheus_client
    - prometheus_client.bridge
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/prometheus/client_python
  license: Apache-2.0
  summary: Python client for the Prometheus monitoring system
  license_family: Apache
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - jessicaaustin
    - kwilcox
    - ocefpaf
